# POR:Medina Isiordia Pedro Luis
# No. Control: 18212218
# Archivo Makefile: Codigo que compila un programa definido.
# Fecha: 02/12/2020
# Materia: Lenguajez de interfaz.

# Makefile
all: holamundo

holamundo:
	as -o holamundo.o holamundo.s
	ld holamundo.o -o holamundo

clean:
	rm -vf holamundo *.o
